In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('ecommerce_sales_analytics_5000.csv', parse_dates=['order_date'])
print(df.head())

   order_id order_date  customer_id product_category region  quantity  \
0     10001 2022-01-01         1102           Beauty  South         7
1     10002 2022-01-02         1435         Clothing  South         7
2     10003 2022-01-03         1860           Beauty   East         3
3     10004 2022-01-04         1270      Electronics   West         5
4     10005 2022-01-05         1106         Clothing   West         5

   unit_price  discount payment_method  delivery_days  customer_rating  \
0      373.65      0.28         Wallet             10              4.7
1       47.74      0.09           Card              6              3.9
2      311.28      0.31            COD              6              2.5
3      524.47      0.02         Wallet              6              1.6
4      139.87      0.33         Wallet              4              4.9

   revenue
0  1883.20
1   304.10
2   644.35
3  2569.90
4   468.56

In [5]:
# verify dataset before analysis
df.shape

(5000, 12)

In [6]:
df.describe()

,order_id,order_date,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2028-11-04 12:00:00,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
min,10001.000000,2022-01-01 00:00:00,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,2025-06-03 18:00:00,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,2028-11-04 12:00:00,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,2032-04-07 06:00:00,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,2035-09-09 00:00:00,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000
std,1443.520003,NaN,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219

In [7]:
df[['unit_price', 'revenue']].describe()

        unit_price      revenue
count  5000.000000  5000.000000
mean    308.418774  1021.955148
std     169.259369   825.584219
min      15.150000    11.210000
25%     161.895000   354.527500
50%     309.890000   796.650000
75%     455.557500  1515.690000
max     599.960000  4119.330000

In [8]:
# quantiles
df['revenue'].quantile([0.25, 0.5, 0.75])

0.25     354.5275
0.50     796.6500
0.75    1515.6900
Name: revenue, dtype: float64

In [ ]:
# means and median 
print("Mean Revenue:", df['revenue'].mean())
print("Median Revenue:", df['revenue'].median())
# indetifying skewness
df['revenue'].skew()      # positive skewness indicates a long tail on the right side of the distribution, while negative skewness indicates a long tail on the left side. A skewness value close to 0 suggests a relatively symmetric distribution.

Mean Revenue: 1021.955148
Median Revenue: 796.65

np.float64(1.0017064603000962)

In [10]:
# category level descriptive statistics
df.groupby('product_category')['revenue'].describe()

,count,mean,std,min,25%,50%,75%,max
product_category,,,,,,,,
Beauty,723.0,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
Clothing,1531.0,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
Electronics,1777.0,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
Home,969.0,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56

In [12]:
# find highest mean 
df.groupby('product_category')['revenue'].mean()

product_category
Beauty         1059.281992
Clothing       1000.608570
Electronics    1029.768835
Home           1013.502497
Name: revenue, dtype: float64

In [13]:
# using IQR to understand spread and identify outliers
Q1 = df['revenue'].quantile(0.25)
Q3 = df['revenue'].quantile(0.75)
IQR = Q3 - Q1
Q1, Q3, IQR

(np.float64(354.5275), np.float64(1515.69), np.float64(1161.1625000000001))

In [14]:
(Q3 > Q1) and (IQR > 0)

np.True_